Chat/Pages/Conversations.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Chat.Services;
using Microsoft.AspNetCore.Mvc.Rendering;
using Chat.Data;
using Microsoft.AspNetCore.Identity;

namespace Chat
{
    public class ConversationsModel : PageModel
    {
        DataProvider _dp { get; set; }
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;
        public string UserID { get; set; }
        public ConversationsModel(DataProvider dp, UserManager<IdentityUser> userManager,
            SignInManager<IdentityUser> signInManager)
        {
            _dp = dp;
            _userManager = userManager;
            _signInManager = signInManager;
        }
        [BindProperty(SupportsGet = true)]
        public string UserFilter { get; set; }
        public List<SelectListItem> UserList
        {
            get
            {
                List<SelectListItem> selectListItems = new List<SelectListItem>();
                foreach (var item in _dp.GetUsers())
                {
                    selectListItems.Add(new SelectListItem(item.UserName, item.Id));
                }
                return selectListItems;
            }
        }
        [BindProperty]
        public string Message { get; set; }
        public IEnumerable<Message> Messages { get; set; }

        public IActionResult OnPostFilter()
        {
            _dp.Filter = UserFilter;
            return RedirectToPage("./Conversations");
        }
        public async Task<IActionResult> OnGet()
        {
            //Don't ask me why I didn't make this a separate function. Ask the fucking C# why it doesn't recognise the fucking page handlers
            if (UserFilter != null)
            {
                _dp.Filter = UserFilter;
            }
            UserID = "";
            var user = await _userManager.GetUserAsync(User);
            if (user != null)
            {
                UserID = user.Id;
                if (_dp.Filter == null)
                {
                    Messages = null;
                    return null;
                }
                else
                {
                    if (user.Id != "")
                    {
                        Messages = _dp.GetConversation(_dp.Filter, user.Id).Messages;
                    }
                    return null;
                }
            }
            return null;
        }
        public async Task<IActionResult> OnPost()
        {
            UserID = "";
            var user = await _userManager.GetUserAsync(User);
            if (user != null && Message != "")
            {
                UserID = user.Id;
                _dp.SendMessage(_dp.GetConversation(UserFilter, user.Id), user, Message);
            }
            Message = "";
            return Page();
        }
    }
}

Chat/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Chat.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Chat/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Chat.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Chat/Pages/Conversations.cshtml
@page
@model Chat.ConversationsModel
@{
    ViewData["Title"] = "Conversations";
}

@if (Model.UserID != "")
{
    <form asp-page="./Conversations" method="post" class="form-inline">
        <label class="sr-only" for="Search">Filtr</label>
        <select class="form-control mb-2 mr-sm-2" asp-for="UserFilter" asp-items="Model.UserList">
        </select>
        <textarea asp-for="Message">Message</textarea>
        <input type="submit" value="Send"  class="btn btn-primary mb-2 mr-1" />
        <input asp-page-handler="Filter" type="submit" value="Search" class="btn btn-primary mb-2 mr-1" />
    </form>
    @if (Model.Messages != null)
    {
        <div>
            @foreach (var i in Model.Messages)
            {
                @if (i.Sender.Id == Model.UserID)
                {
                    <p class="rounded-circle message-sent">
                        @i.Body
                    </p>
                }
                else
                {
                    <p class="rounded-circle message-received">
                        @i.Body
                    </p>
                }
            }
        </div>
        

    }
    <form asp-page="./Conversations" method="post" class="form-inline">
        
    </form>
}
else
{
    <p>To display your conversations, you must be logged in.</p>
}

Chat/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>